[client]
# Hide the automatic page navigation
showSidebarNavigation = false

[ui]
# Hide the top-right menu
hideTopBar = false

[server]
# Enable CORS for API calls
enableCORS = false
enableXsrfProtection = false
